### ISSUE TITLE
rm env zone

### ISSUE THREAD

**Issue by le9i0nx** [flant/clusterissuer-regru#5]
the zone can be calculated through requests to api
https://www.reg.ru/reseller/api2doc#zone_nop
you also need to consider dns delegation in _acme-challenge https://letsencrypt.org/docs/challenge-types/

**Comment by le9i0nx** [comment]
check zone in challengeRequest.ResolvedFQDN
1.  _acme-challenge.test.ru
2. test.ru

**Comment by wildGecko** [comment]
Why delete a zone from ENV? It is passed to the request in such a way that it explicitly specifies where to create a record, since you can have multiple dnames.
We will study the question about delegation.

**Comment by le9i0nx** [comment]
if you delete the env zone, then you can renew the certificate for any domain to which you have access and not create a ClusterIssuer list for each domain

**Comment by c0rnoTa** [comment]
@le9i0nx you are welcome to review my PR https://github.com/flant/cert-manager-webhook-regru/pull/8 too.

**Comment by wildGecko** [comment]
I have accepted PR.
